name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: go build -o my-app ./cmd/server/main.go

    - name: Build Docker image
      run: |
        docker build -t my-app-image .

